server:
  port: 8082

logging:
  level:
    com.hlh.content.openfeign.UserService: debug

rocketmq:
  name-server: 124.221.232.15:9876
  producer:
    group: test-group
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.232.15:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        namespace: dev
        register-enabled: true

