server:
  port: 8152
spring:
  application:
    name: cloud-shopcart-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.232.15:3306/test_distribution_cart_db
    username: root
    password: hlh320123678

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
seata:
  application-id: shopcart-service-demo
  enabled: true
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: public
      group: DEFAULT_GROUP
      cluster: default
      username: nacos
      password: nacos
  tx-service-group: seata-server-group
  service:
    vgroup-mapping:
      seata-server-group: default
  enable-auto-data-source-proxy: false
