server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 124.221.232.15:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        register-enabled: true
  jpa:
    open-in-view: false
jwt:
  secret: aaaaaaaaaabbbbbbbbbbbcccccccccccddddddd
  expire-time-in-second: 1209600

rocketmq:
  name-server: 124.221.232.15:9876