server:
  port: 10001

spring:
  cloud:
    nacos:         #nacos??
      discovery:
        namespace: dev  #????
        server-addr: 124.221.232.15:8848   #nacos??
        password: nacos
        username: nacos
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        register-enabled: true
