server:
  port: 8083

spring:
  application:
    name: gateway #????
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true   #??????
#          lower-case-service-id: true
      routes:   # ????????
        - id: user-service   # ??id
          order: 1      #???
          predicates:   #????
            - Path=/users/**
          uri: http://localhost:8081   #??url
        - id: content-service
          order: 1
          predicates:
            - Path=/shares/**
          uri: http://localhost:8082
        - id: content-service
          order: 1
          predicates:
            - Path=/notices/**
          uri: http://localhost:8082
    nacos:         #nacos??
      discovery:
        namespace: dev  #????
        server-addr: 124.221.232.15:8848   #nacos??
      password: nacos
      username: nacos
