spring:
  application:
    name: repair-service
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.232.15:8848
      username: nacos
      password: nacos
  datasource:
    url: jdbc:mysql://124.221.232.15:3306/share
    hikari:
      username: root
      password: hlh320123678
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8086
