server:
  port: 9002
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 500MB
  application:
    name: file-service
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.232.15:8848
      password: nacos
      username: nacos
# MinIo?????
minio:
  endpoint: http://124.221.232.15:9090
  accessKey: admin
  secretKey: admin123


