server:
  port: 8082
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 500MB
  redis:
    host: 47.96.31.161
    port: 6379
  mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.120.36:8848
        namespace: test
      password: nacos
      username: nacos
# MinIo文件服务器
minio:
  endpoint: http://124.221.232.15:9090
  accessKey: admin
  secretKey: admin123

